llm:
  provider: "litellm"
  model: "gpt-4o-mini"
  temperature: 0.1
  max_tokens: 4000
  budget: 5.0
  models:
    gpt-4o-mini:
      provider: "litellm"
      model: "gpt-4o-mini"
      temperature: 0.1
      max_tokens: 4000

orchestrator:
  max_iterations: 10
  use_multi_agent: true
  
tools:
  enabled:
    - "filesystem"
    - "shell"
    - "git"
    - "search"
    - "todos"
    - "ask_supervisor"

repository:
  index_on_start: false
  
session:
  persist: true