llm:
  provider: litellm
  model: ""  # No default model - users must select one
  api_base: ""
  budget: 1.0
  temperature: 0.1
  max_tokens: 4000

sandbox:
  type: venv
  timeout: 30
  max_memory: 512  # MB
  allow_network: false

session:
  persist: true
  max_context: "auto"  # Automatically determined based on model capabilities
  session_dir: ~/.EQUITR-coder/sessions

repository:
  index_on_start: true
  ignore_patterns:
    - "*.pyc"
    - "__pycache__"
    - ".git"
    - "node_modules"
    - ".venv"
    - "venv"
    - "*.log"

orchestrator:
  max_iterations: 20
  error_retry_limit: 3
  error_retry_delay: 1.0
  supervisor_model: "o3"
  worker_model: "moonshot/kimi-k2-0711-preview"

profiles:
  default: default
  available:
    - ml_researcher
    - app_developer
