llm:
  max_tokens: 4000
  model: moonshot/kimi-k2-0711-preview
  temperature: 0.1
orchestrator:
  debug: true
  max_cost: 5.0
  max_iterations: 20
  timeout_seconds: 300
  use_multi_agent: false
session:
  max_context: 8000
  session_dir: testing/comprehensive_tests/run_20250804_190343/multi_agent_parallel_envs/env_multi_agent_parallel_audit/sessions
tools:
  disabled: []
  enabled:
  - read_file
  - write_file
  - list_files
  - grep_search
  - shell
  - git_status
  - git_diff
  - git_commit
  - create_todo
  - update_todo
  - list_todos
